package com.example.roomdb;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.lifecycle.ViewModelProvider;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewpager2.widget.ViewPager2;

import android.content.Intent;
import android.os.Bundle;
import android.os.Parcelable;
import android.view.View;
import android.widget.EditText;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {
private RecyclerView recyclerView;
private Adapter adapter;
private ViewModel notesViewModel;

static int ADD_NOTES_REQUEST_CODE=1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        recyclerView=findViewById(R.id.recyclerView);

        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new GridLayoutManager(this,2));//spancount is the number of columns
        adapter=new Adapter(this);
        recyclerView.setAdapter(adapter);

        /*
         When your Activity first starts,
         the ViewModelProviders will create the ViewModel.
         When the activity is destroyed, for example through a configuration change,
         the ViewModel persists. When the activity is re-created,
         the ViewModelProviders return the existing ViewModel
         */
//        notesViewModel= new ViewModelProvider(this).get(ViewModel.class);-> this can't create a instance of viewModel
        notesViewModel = new ViewModelProvider(this, new ViewModelProvider.AndroidViewModelFactory(getApplication())).get(ViewModel.class);
        //Everytime a change os observed,a arrayList is generated by the name of notes and is passed to the updateList method of the Adapter
        notesViewModel.getNotes().observe(this,notes->adapter.setNotesList(notes));


    }

    public void addNewNotes(View view) {
        Intent intent=new Intent(this,AddNotes.class);
        startActivityForResult(intent,ADD_NOTES_REQUEST_CODE);//starts the activity in hope of a result

    }


    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if(resultCode==RESULT_OK && requestCode==ADD_NOTES_REQUEST_CODE)
        {
            EntityNotes notes=new EntityNotes(data.getStringExtra(AddNotes.INTENT_NAME));//id is auto-generated
            notesViewModel.insert(notes);
            Toast.makeText(this, "Saved Successfully", Toast.LENGTH_SHORT).show();
        }else
            Toast.makeText(this, "Can't save !", Toast.LENGTH_SHORT).show();
    }
}